
        ;; BBC Micro MOS entry points.

OSCLI   EQU  &FFF7
OSBYTE	EQU  &FFF4
OSWORD	EQU  &FFF1
OSWRCH	EQU  &FFEE
OSNEWL  EQU  &FFE7
OSASCI  EQU  &FFE3
OSRDCH  EQU  &FFE0
OSFILE	EQU  &FFDD
OSARGS  EQU  &FFDA
OSBGET  EQU  &FFD7
OSBPUT  EQU  &FFD4
OSGBPB  EQU  &FFD1
OSFIND  EQU  &FFCE
NVWRCH  EQU  &FFCB
NVRDCH  EQU  &FFC8
GSREAD  EQU  &FFC5
GSINIT  EQU  &FFC2
OSEVEN  EQU  &FFBF
OSRDRM  EQU  &FFB9
VDURAW  EQU  &FFBC

ACCCON  EQU  &FE34
